'use client'

import { AppLayout } from '@/components/app-layout'
import { Button } from '@/components/ui/button'
import { useState } from 'react'
import jsPDF from 'jspdf'
import { FileText } from 'lucide-react'

export default function DocumentsPage() {
  const [activeTab, setActiveTab] = useState<'nda' | 'lease'>('nda')

  // NDA State
  const [ndaForm, setNdaForm] = useState({
    partyAName: '',
    partyAAddress: '',
    partyBName: '',
    partyBAddress: '',
    effectiveDate: '',
    termMonths: '',
  })

  // Lease State
  const [leaseForm, setLeaseForm] = useState({
    landlordName: '',
    tenantName: '',
    propertyAddress: '',
    monthlyRent: '',
    deposit: '',
    startDate: '',
    termMonths: '',
  })

  const generateNDAPDF = () => {
    if (!ndaForm.partyAName || !ndaForm.partyBName || !ndaForm.effectiveDate) {
      alert('Please fill in all required fields')
      return
    }

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    let yPos = 20

    // Header
    doc.setFont('Arial', 'bold')
    doc.setFontSize(16)
    doc.text('NON-DISCLOSURE AGREEMENT', pageWidth / 2, yPos, { align: 'center' })
    yPos += 15

    // Parties
    doc.setFontSize(10)
    doc.setFont('Arial', 'normal')
    doc.text(`This Non-Disclosure Agreement is entered into on ${ndaForm.effectiveDate}`, 20, yPos)
    yPos += 10
    doc.text(`BETWEEN: ${ndaForm.partyAName}`, 20, yPos)
    yPos += 5
    doc.text(`Address: ${ndaForm.partyAAddress}`, 25, yPos)
    yPos += 8
    doc.text(`AND: ${ndaForm.partyBName}`, 20, yPos)
    yPos += 5
    doc.text(`Address: ${ndaForm.partyBAddress}`, 25, yPos)
    yPos += 15

    // Terms
    doc.setFont('Arial', 'bold')
    doc.text('1. CONFIDENTIAL INFORMATION', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const terms1 = doc.splitTextToSize(
      'The Disclosing Party agrees to disclose certain confidential information to the Receiving Party. This information includes but is not limited to business plans, financial data, client lists, technical information, and trade secrets.',
      pageWidth - 40
    )
    doc.text(terms1, 20, yPos)
    yPos += terms1.length * 4 + 8

    doc.setFont('Arial', 'bold')
    doc.text('2. OBLIGATIONS OF RECEIVING PARTY', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const terms2 = doc.splitTextToSize(
      'The Receiving Party agrees to keep all Confidential Information in strict confidence and not disclose it to any third party without prior written consent.',
      pageWidth - 40
    )
    doc.text(terms2, 20, yPos)
    yPos += terms2.length * 4 + 8

    doc.setFont('Arial', 'bold')
    doc.text('3. TERM', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    doc.text(`This Agreement shall remain in effect for ${ndaForm.termMonths} months from the Effective Date.`, 20, yPos)
    yPos += 10

    doc.setFont('Arial', 'bold')
    doc.text('4. GOVERNING LAW', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const terms3 = doc.splitTextToSize(
      'This Agreement shall be governed by and construed in accordance with the laws of Botswana, without regard to conflicts of law principles.',
      pageWidth - 40
    )
    doc.text(terms3, 20, yPos)
    yPos += terms3.length * 4 + 12

    // Signature blocks
    doc.setFont('Arial', 'bold')
    doc.text('SIGNATURES:', 20, yPos)
    yPos += 12

    doc.setFont('Arial', 'normal')
    doc.text('_________________________', 20, yPos)
    doc.text('_________________________', pageWidth / 2 + 10, yPos)
    yPos += 5
    doc.text(`${ndaForm.partyAName}`, 20, yPos)
    doc.text(`${ndaForm.partyBName}`, pageWidth / 2 + 10, yPos)

    // Footer
    doc.setFontSize(8)
    doc.text(
      `Generated by Gabs Legal Tech - ${new Date().toLocaleDateString('en-BW')}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )

    const filename = `NDA_${ndaForm.partyAName.replace(/\s+/g, '_')}_${ndaForm.partyBName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(filename)
  }

  const generateLeasePDF = () => {
    if (!leaseForm.landlordName || !leaseForm.tenantName || !leaseForm.propertyAddress || !leaseForm.monthlyRent) {
      alert('Please fill in all required fields')
      return
    }

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    let yPos = 20

    // Header
    doc.setFont('Arial', 'bold')
    doc.setFontSize(16)
    doc.text('RESIDENTIAL LEASE AGREEMENT', pageWidth / 2, yPos, { align: 'center' })
    yPos += 15

    // Parties
    doc.setFontSize(10)
    doc.setFont('Arial', 'normal')
    doc.text(`This Lease Agreement is entered into on ${leaseForm.startDate}`, 20, yPos)
    yPos += 10
    doc.text(`LANDLORD: ${leaseForm.landlordName}`, 20, yPos)
    yPos += 8
    doc.text(`TENANT: ${leaseForm.tenantName}`, 20, yPos)
    yPos += 8
    doc.text(`PROPERTY: ${leaseForm.propertyAddress}`, 20, yPos)
    yPos += 15

    // Terms
    doc.setFont('Arial', 'bold')
    doc.text('1. RENTAL TERMS', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    doc.text(`Monthly Rent: P${parseFloat(leaseForm.monthlyRent).toFixed(2)}`, 20, yPos)
    yPos += 5
    doc.text(`Security Deposit: P${parseFloat(leaseForm.deposit).toFixed(2)}`, 20, yPos)
    yPos += 5
    doc.text(`Lease Term: ${leaseForm.termMonths} months`, 20, yPos)
    yPos += 12

    doc.setFont('Arial', 'bold')
    doc.text('2. PAYMENT OBLIGATIONS', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const payment = doc.splitTextToSize(
      'Tenant shall pay rent in full and on time each month. Late payments will accrue a 10% penalty. VAT (15%) is added to rent for BURS compliance.',
      pageWidth - 40
    )
    doc.text(payment, 20, yPos)
    yPos += payment.length * 4 + 8

    doc.setFont('Arial', 'bold')
    doc.text('3. QUIET ENJOYMENT', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const quiet = doc.splitTextToSize(
      'Landlord covenants to provide quiet enjoyment of the property to Tenant, free from interference.',
      pageWidth - 40
    )
    doc.text(quiet, 20, yPos)
    yPos += quiet.length * 4 + 8

    doc.setFont('Arial', 'bold')
    doc.text('4. REPAIRS AND MAINTENANCE', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const repairs = doc.splitTextToSize(
      'Landlord shall maintain the property in good repair and habitable condition. Tenant shall maintain minor repairs and keep property clean.',
      pageWidth - 40
    )
    doc.text(repairs, 20, yPos)
    yPos += repairs.length * 4 + 8

    doc.setFont('Arial', 'bold')
    doc.text('5. TERMINATION', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    doc.text('Either party may terminate this lease by providing 2 months written notice.', 20, yPos)
    yPos += 10

    doc.setFont('Arial', 'bold')
    doc.text('6. GOVERNING LAW', 20, yPos)
    yPos += 8
    doc.setFont('Arial', 'normal')
    const law = doc.splitTextToSize(
      'This Agreement shall be governed by the laws of Botswana.',
      pageWidth - 40
    )
    doc.text(law, 20, yPos)
    yPos += law.length * 4 + 12

    // Signature blocks
    doc.setFont('Arial', 'bold')
    doc.text('SIGNATURES:', 20, yPos)
    yPos += 12

    doc.setFont('Arial', 'normal')
    doc.text('_________________________', 20, yPos)
    doc.text('_________________________', pageWidth / 2 + 10, yPos)
    yPos += 5
    doc.text(leaseForm.landlordName, 20, yPos)
    doc.text(leaseForm.tenantName, pageWidth / 2 + 10, yPos)

    // Footer
    doc.setFontSize(8)
    doc.text(
      `Generated by Gabs Legal Tech - ${new Date().toLocaleDateString('en-BW')}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )

    const filename = `Lease_${leaseForm.tenantName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(filename)
  }

  return (
    <AppLayout>
      <div className="space-y-6">
        <h1 className="text-3xl font-bold text-white">Document Generators</h1>

        {/* Tabs */}
        <div className="flex gap-2 border-b border-[#222]">
          <button
            onClick={() => setActiveTab('nda')}
            className={`px-4 py-3 font-medium transition-colors ${
              activeTab === 'nda'
                ? 'border-b-2 border-[#00FF88] text-[#00FF88]'
                : 'text-gray-400 hover:text-white'
            }`}
          >
            NDA Generator
          </button>
          <button
            onClick={() => setActiveTab('lease')}
            className={`px-4 py-3 font-medium transition-colors ${
              activeTab === 'lease'
                ? 'border-b-2 border-[#00FF88] text-[#00FF88]'
                : 'text-gray-400 hover:text-white'
            }`}
          >
            Lease Agreement
          </button>
        </div>

        {/* NDA Tab */}
        {activeTab === 'nda' && (
          <div className="bg-[#1a1a1a] rounded-lg p-6 border border-[#222]">
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Party A Name *</label>
                  <input
                    type="text"
                    value={ndaForm.partyAName}
                    onChange={(e) => setNdaForm({ ...ndaForm, partyAName: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter party A name"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Party A Address *</label>
                  <input
                    type="text"
                    value={ndaForm.partyAAddress}
                    onChange={(e) => setNdaForm({ ...ndaForm, partyAAddress: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter party A address"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Party B Name *</label>
                  <input
                    type="text"
                    value={ndaForm.partyBName}
                    onChange={(e) => setNdaForm({ ...ndaForm, partyBName: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter party B name"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Party B Address *</label>
                  <input
                    type="text"
                    value={ndaForm.partyBAddress}
                    onChange={(e) => setNdaForm({ ...ndaForm, partyBAddress: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter party B address"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Effective Date *</label>
                  <input
                    type="date"
                    value={ndaForm.effectiveDate}
                    onChange={(e) => setNdaForm({ ...ndaForm, effectiveDate: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Term (months) *</label>
                  <input
                    type="number"
                    value={ndaForm.termMonths}
                    onChange={(e) => setNdaForm({ ...ndaForm, termMonths: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter term in months"
                  />
                </div>
              </div>
              <Button
                onClick={generateNDAPDF}
                className="w-full bg-[#00FF88] text-black hover:bg-[#00DD77] font-bold py-2"
              >
                <FileText className="h-4 w-4 mr-2" />
                Generate NDA PDF
              </Button>
            </div>
          </div>
        )}

        {/* Lease Tab */}
        {activeTab === 'lease' && (
          <div className="bg-[#1a1a1a] rounded-lg p-6 border border-[#222]">
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Landlord Name *</label>
                  <input
                    type="text"
                    value={leaseForm.landlordName}
                    onChange={(e) => setLeaseForm({ ...leaseForm, landlordName: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter landlord name"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Tenant Name *</label>
                  <input
                    type="text"
                    value={leaseForm.tenantName}
                    onChange={(e) => setLeaseForm({ ...leaseForm, tenantName: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter tenant name"
                  />
                </div>
                <div className="md:col-span-2">
                  <label className="block text-gray-400 text-sm mb-2">Property Address *</label>
                  <input
                    type="text"
                    value={leaseForm.propertyAddress}
                    onChange={(e) => setLeaseForm({ ...leaseForm, propertyAddress: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter property address"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Monthly Rent (P) *</label>
                  <input
                    type="number"
                    value={leaseForm.monthlyRent}
                    onChange={(e) => setLeaseForm({ ...leaseForm, monthlyRent: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter monthly rent"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Security Deposit (P) *</label>
                  <input
                    type="number"
                    value={leaseForm.deposit}
                    onChange={(e) => setLeaseForm({ ...leaseForm, deposit: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter security deposit"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Lease Start Date *</label>
                  <input
                    type="date"
                    value={leaseForm.startDate}
                    onChange={(e) => setLeaseForm({ ...leaseForm, startDate: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-2">Lease Term (months) *</label>
                  <input
                    type="number"
                    value={leaseForm.termMonths}
                    onChange={(e) => setLeaseForm({ ...leaseForm, termMonths: e.target.value })}
                    className="w-full bg-[#0a0a0a] border border-[#222] rounded px-3 py-2 text-white focus:outline-none focus:border-[#00FF88]"
                    placeholder="Enter lease term in months"
                  />
                </div>
              </div>
              <Button
                onClick={generateLeasePDF}
                className="w-full bg-[#00FF88] text-black hover:bg-[#00DD77] font-bold py-2"
              >
                <FileText className="h-4 w-4 mr-2" />
                Generate Lease PDF
              </Button>
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  )
}
